# Generated by Django 5.0.6 on 2024-06-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_consulta_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.CharField(choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30')], max_length=100),
        ),
    ]
