# Generated by Django 5.0.6 on 2024-06-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_consulta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
