# Generated by Django 5.0.6 on 2024-06-05 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_rename_usuario_consulta_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mes',
            field=models.CharField(choices=[('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='servico',
            field=models.CharField(choices=[('clareamento', 'Clareamento dental'), ('facetas', 'Facetas'), ('lentes', 'Lentes de Contato'), ('canal', 'Tratamento de Canal'), ('gengiva', 'Tratamento de Gengiva')], max_length=100),
        ),
    ]
