# Generated by Django 5.0.6 on 2024-06-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_alter_consulta_cliente_alter_consulta_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='mes',
            field=models.CharField(choices=[('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='servico',
            field=models.CharField(choices=[('Clareamento dental', 'Clareamento dental'), ('Facetas', 'Facetas'), ('Lentes de Contato', 'Lentes de Contato'), ('Tratamento de Canal', 'Tratamento de Canal'), ('Tratamento de Gengiva', 'Tratamento de Gengiva')], max_length=100),
        ),
    ]
