# Generated by Django 5.0.6 on 2024-06-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_alter_consulta_mes_alter_consulta_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='dia',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
